---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Create namespace
      k8s:
        name: "{{ eck_namespace | d('elastic-stack') }}"
        api_version: v1
        kind: Namespace
        state: "present"
      when: "state|d('present') == 'present'"
      tags:
        - namespace
        - ns

    - name: Install Elastic Stack
      import_role:
        name: elastic-stack
      tags:
        - elastic-stack
