---
# - name: Print k8s manifest
#   template:
#     src: "{{ item }}.j2"
#     dest: "{{ item }}"
#   loop:
#     - kibana.yml
#     - elasticsearch.yml
#   tags: debug

- name: Elasticsearch objects state="{{ state | d('present') }}"
  k8s:
    state: "{{ state | d('present') }}"
    apply: true
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.deploy | d(true)
  loop:
    - name: elasticsearch.yml.j2
  tags: elastic

- name: Kibana objects state="{{ state | d('present') }}"
  k8s:
    state: "{{ state | d('present') }}"
    apply: true
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.deploy | d(true)
  loop:
    - name: kibana.yml.j2
    - name: kibana_route.yml.j2
  tags: kibana
